# Generated by Django 4.1.5 on 2023-02-18 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_mayorista_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='models_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='producto',
        ),
    ]
