# Generated by Django 4.1.5 on 2023-02-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_models_producto_delete_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models_producto',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
    ]
